language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^10.4
    - php: 7.3
      env: TYPO3_VERSION=^10.4
    - php: 7.4
      env: TYPO3_VERSION=^10.4

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - travis@extco.de

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms-core=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB="$PWD/.build/Web"

script:
  - >
    echo;
    echo "Running unit tests";
    .build/bin/phpunit --colors -c Build/UnitTests.xml

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    echo "Running php-cs-fixer";
    .build/bin/php-cs-fixer fix --config=Build/.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection ./;

  - >
    echo;
    typo3DatabaseDriver=pdo_sqlite .build/bin/phpunit -c Build/FunctionalTests.xml
